---
substitutions:
  name: esp32-s3-box-3
  friendly_name: ESP32 S3 Box 3
  loading_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/loading_320_240.png
  idle_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/idle_320_240.png
  listening_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/listening_320_240.png
  thinking_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/thinking_320_240.png
  replying_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/replying_320_240.png
  error_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/error_320_240.png
  timer_finished_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/timer_finished_320_240.png

  loading_illustration_background_color: "000000"
  idle_illustration_background_color: "000000"
  listening_illustration_background_color: "FFFFFF"
  thinking_illustration_background_color: "FFFFFF"
  replying_illustration_background_color: "FFFFFF"
  error_illustration_background_color: "000000"

  voice_assist_idle_phase_id: "1"
  voice_assist_listening_phase_id: "2"
  voice_assist_thinking_phase_id: "3"
  voice_assist_replying_phase_id: "4"
  voice_assist_not_ready_phase_id: "10"
  voice_assist_error_phase_id: "11"
  voice_assist_muted_phase_id: "12"
  voice_assist_timer_finished_phase_id: "20"

  # These unique characters have been extracted from every test file of every language available on https://github.com/home-assistant/intents (14 March 2024)
  # However, the Figtree font only contains Latin characters, so there is no point using this.

  allowed_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ¿ÁÂÄÅÉÖÚßàáâãäåæçèéêëìíîðñòóôõöøùúûüýþāăąćčďĐđēėęěğĮįıļľŁłńňőřśšťũūůűųźŻżŽžơưșțΆΈΌΐΑΒΓΔΕΖΗΘΚΜΝΠΡΣΤΥΦάέήίαβγδεζηθικλμνξοπρςστυφχψωϊόύώАБВГДЕЖЗИКЛМНОПРСТУХЦЧШЪЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёђєіїјљњћאבגדהוזחטיכלםמןנסעפץצקרשת،ءآأإئابةتجحخدذرزسشصضطظعغفقكلمنهوىيٹپچڈکگںھہیےংকচতধনফবযরলশষস়ািু্చయలిెొ్ംഅആഇഈഉഎഓകഗങചജഞടഡണതദധനപഫബഭമയരറലളവശസഹാിീുൂെേൈ്ൺൻർൽൾაბგდევზთილმნოპრსტუფქყშჩცძჭხạảấầẩậắặẹẽếềểệỉịọỏốồổỗộớờởợụủứừửữựỳ—、的一是了我不人在他有这个上们来到时大地为子中你说生国年着就那和要她出也得里后自以会家可下而过天去能对小多然于心学么之都好看起发当没成只如事把还用第样道想作种开美总从无情己面最女但现前些所同日手又行意动方期它头经长儿回位分爱老因很给名法间斯知世什两次使身者被高已亲其进此话常与活正感见明问力理尔点文几定本公特做外孩相西果走将月十实向声车全信重三机工物气每并别真打太新比才便夫再书部水像眼等体却加电主界门利海受听表德少克代员许先口由死安写性马光白或住难望教命花结乐色更拉东神记处让母父应直字场平报友关放至张认接告入笑内英军候民岁往何度山觉路带万男边风解叫任金快原吃妈变通师立象数四失满战远格士音轻目条呢病始达深完今提求清王化空业思切怎非找片罗钱吗语元喜曾离飞科言干流欢约各即指合反题必该论交终林请医晚制球决传画保读运及则房早院量苦火布品近坐产答星精视五连司巴奇管类未朋且婚台夜青北队久乎越观落尽形影红爸百令周吧识步希亚术留市半热送兴造谈容极随演收首根讲整式取照办强石古华拿计您装似足双妻尼转诉米称丽客南领节衣站黑刻统断福城故历惊脸选包紧争另建维绝树系伤示愿持千史谁准联妇纪基买志静阿诗独复痛消社算义竟确酒需单治卡幸兰念举仅介钟怕共毛句息功官待究跟穿室易游程号居考突皮哪费倒价图具刚脑永歌响商礼细专黄块脚味灵改据般破引食仍存众注笔甚某沉血备习校默务土微娘须试怀料调广苏显赛查密议底列富梦错座参八除跑亮假印设线温虽掉京初养香停际致阳纸李纳验助激够严证帝饭忘趣支春集丈木研班普导顿睡展跳获艺六波察群皇段急庭创区奥器谢弟店否害草排背止组州朝封睛板角况曲馆育忙质河续哥呼若推境遇雨标姐充围案伦护冷警贝著雪索剧啊船险烟依斗值帮汉慢佛肯闻唱沙局伯族低玩资屋击速顾泪洲团圣旁堂兵七露园牛哭旅街劳型烈姑陈莫鱼异抱宝权鲁简态级票怪寻杀律胜份汽右洋范床舞秘午登楼贵吸责例追较职属渐左录丝牙党继托赶章智冲叶胡吉卖坚喝肉遗救修松临藏担戏善卫药悲敢靠伊村戴词森耳差短祖云规窗散迷油旧适乡架恩投弹铁博雷府压超负勒杂醒洗采毫嘴毕九冰既状乱景席珍童顶派素脱农疑练野按犯拍征坏骨余承置彩灯巨琴免环姆暗换技翻束增忍餐洛塞缺忆判欧层付阵玛批岛项狗休懂武革良恶恋委拥娜妙探呀营退摇弄桌熟诺宣银势奖宫忽套康供优课鸟喊降夏困刘罪亡鞋健模败伴守挥鲜财孤枪禁恐伙杰迹妹遍盖副坦牌江顺秋萨菜划授归浪听凡预奶雄升编典袋莱含盛济蒙棋端腿招释烧误가간감갔강개거게겨결경고공과관그금급기길깥꺼껐꼽나난내네놀누는능니다닫담대더데도동됐되된됨둡드든등디때떤뜨라래러렇렌려로료른를리림링마많명몇모무문물뭐바밝방배변보부불블빨뽑사산상색서설성세센션소쇼수스습시신실싱아안않알았애야어얼업없었에여연열옆오온완외왼요운움워원위으은을음의이인일임입있작잠장재전절정제져조족종주줄중줘지직진짐쪽차창천최추출충치침커컴켜켰쿠크키탁탄태탬터텔통트튼티파팬퍼폰표퓨플핑한함해했행혀현화활후휴힘，？"  micro_wake_word_model: okay_nabu

  idle_color: "0x2C2C2C"
  listening_color: "0xFF9800"
  thinking_color: "0x2196F3"
  replying_color: "0x4CAF50"
  error_color: "0xF44336"
  loading_color: "0x616161"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  min_version: 2024.12.0

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: lv0cBuI4bl/CnmZcn7D6bMWq2cgjyUxpIrI77vnX5oA=

ota:
  - platform: esphome

logger:

voice_assistant:
  id: va
  microphone: mic
  speaker: speaker
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_listening:
    - display.set_page: listening_page
  on_thinking:
    - display.set_page: thinking_page
  on_replying:
    - display.set_page: replying_page
  on_error:
    - display.set_page: error_page
  on_client_connected:
    - display.set_page: idle_page
  on_client_disconnected:
    - display.set_page: no_ha_page

i2s_audio:
  i2s_lrclk_pin: GPIO12
  i2s_bclk_pin: GPIO13

microphone:
  - platform: i2s_audio
    id: mic
    i2s_din_pin: GPIO11
    adc_type: external
    pdm: false

speaker:
  - platform: i2s_audio
    id: speaker
    i2s_dout_pin: GPIO46
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Mute Button"
    on_press:
      - switch.toggle: mute

switch:
  - platform: template
    name: "Mute"
    id: mute
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - voice_assistant.stop
      - lambda: id(va).set_mute(true);
      - display.set_page: muted_page
    on_turn_off:
      - lambda: id(va).set_mute(false);
      - display.set_page: idle_page
  - platform: template
    name: "Display conversation"
    id: display_conversation
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

font:
  - file: "fonts/wqy-microhei.ttf"
    id: font_request
    size: 15
  - file: "fonts/wqy-microhei.ttf"
    id: font_response
    size: 15
  - file: "fonts/wqy-microhei.ttf"
    id: font_timer
    size: 30

image:
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/error_320_240.png"
    id: casita_error
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/idle_320_240.png"
    id: casita_idle
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/listening_320_240.png"
    id: casita_listening
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/thinking_320_240.png"
    id: casita_thinking
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/replying_320_240.png"
    id: casita_replying
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/timer_finished_320_240.png"
    id: casita_timer_finished
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/casita/loading_320_240.png"
    id: casita_initializing
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/error_box_illustrations/error-no-wifi.png"
    id: error_no_wifi
    resize: 320x240
    type: RGB
    transparency: alpha_channel
  - file: "https://github.com/zminde/wake-word-voice-assistants/raw/main/error_box_illustrations/error-no-ha.png"
    id: error_no_ha
    resize: 320x240
    type: RGB
    transparency: alpha_channel

text_sensor:
  - platform: voice_assistant
    id: text_request
    name: "Request"
  - platform: voice_assistant
    id: text_response
    name: "Response"

script:
  - id: draw_timer_timeline
    then:
      # 简化，未修改
      - lambda: |-
          // 原定时器逻辑
  - id: draw_active_timer_widget
    then:
      # 简化，未修改
      - lambda: |-
          // 原定时器逻辑

display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    invert_colors: false
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: never
    pages:
      - id: idle_page
        lambda: |-
          it.fill(id(idle_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_idle), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();
          id(draw_active_timer_widget).execute();
      - id: listening_page
        lambda: |-
          it.fill(id(listening_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_listening), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();
      - id: thinking_page
        lambda: |-
          it.fill(id(thinking_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_thinking), ImageAlign::CENTER);
          if (id(display_conversation).state) {
            it.filled_rectangle(20, 20, 280, 30, Color::WHITE);
            it.rectangle(20, 20, 280, 30, Color::BLACK);
            it.printf(30, 25, id(font_request), Color::BLACK, "%s", id(text_request).state.c_str());
          }
          id(draw_timer_timeline).execute();
      - id: replying_page
        lambda: |-
          it.fill(id(replying_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_replying), ImageAlign::CENTER);
          if (id(display_conversation).state) {
            it.filled_rectangle(20, 20, 280, 30, Color::WHITE);
            it.rectangle(20, 20, 280, 30, Color::BLACK);
            it.filled_rectangle(20, 190, 280, 30, Color::WHITE);
            it.rectangle(20, 190, 280, 30, Color::BLACK);
            it.printf(30, 25, id(font_request), Color::BLACK, "%s", id(text_request).state.c_str());
            it.printf(30, 195, id(font_response), Color::BLACK, "%s", id(text_response).state.c_str());
          }
          id(draw_timer_timeline).execute();
      - id: timer_finished_page
        lambda: |-
          it.fill(id(idle_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_timer_finished), ImageAlign::CENTER);
      - id: error_page
        lambda: |-
          it.fill(id(error_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_error), ImageAlign::CENTER);
      - id: no_ha_page
        lambda: |-
          it.image((it.get_width() / 2), (it.get_height() / 2), id(error_no_ha), ImageAlign::CENTER);
      - id: no_wifi_page
        lambda: |-
          it.image((it.get_width() / 2), (it.get_height() / 2), id(error_no_wifi), ImageAlign::CENTER);
      - id: initializing_page
        lambda: |-
          it.fill(id(loading_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_initializing), ImageAlign::CENTER);
      - id: muted_page
        lambda: |-
          it.fill(Color::BLACK);
          id(draw_timer_timeline).execute();
          id(draw_active_timer_widget).execute();
